run:
  timeout: 15m

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - logcheck
    - makezero
    - misspell
    - nakedret
    - nilnil
    - prealloc
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tagalign
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - whitespace

    # next linters to be enabled:

    # linters to be enabled in the distant future:
    # - cyclop
    # - dupl
    # - funlen
    # - interfacebloat
    # - predeclared
    # - stylecheck
    # - wrapcheck

linters-settings:
  custom:
    logcheck:
      path: tools/logcheck.so
      description: structured logging checker
      original-url: sigs.k8s.io/logtools/logcheck

  gofmt:
    simplify: true

  dupl:
    threshold: 400

  exhaustive:
    check:
      - switch
      - map
    ignore-enum-types: "ResourceName|Atom"
    default-signifies-exhaustive: true

  importas:
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s\.io/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s\.io/apimachinery/pkg/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: kerrors
      - pkg: k8s.io/apimachinery/pkg/apis/meta/internalversion
        alias: metainternalversion

  tagalign:
    order:
      - json
      - yaml
      - xml
      - form

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
